services:
  traefik:
    image: traefik:v2.3
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - ./data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      default:
        ipv4_address: 172.20.5.10 # Fix Traefik IP to be able to map it on the backend

  fuseki:
    image: semapps/jena-fuseki-webacl
    volumes:
      - ./data/fuseki:/fuseki
    ports:
      - '3030:3030'
    expose:
      - '3030'
    environment:
      ADMIN_PASSWORD: ${FUSEKI_PASSWORD}

  activitypods-backend:
    image: activitypods/backend
    depends_on:
      - fuseki
      - redis
    volumes:
      - ./data/backend/logs:/app/backend/logs
      - ./data/backend/jwt:/app/backend/jwt
      - ./data/backend/uploads:/app/backend/uploads
      - ./data/fuseki:/fuseki-data # Needed to allow the backend to access Fuseki data
    expose:
      - '3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN_NAME}`)'
      - 'traefik.http.routers.backend.entrypoints=websecure'
      - 'traefik.http.routers.backend.tls.certresolver=myresolver'
    env_file:
      - .env.backend
      - path: .env.backend.local
        required: false
    # Redirect backend-to-backend calls to Traefik container
    extra_hosts:
      - "${BACKEND_DOMAIN_NAME}:172.20.5.10"
      - "${WTMP_DOMAIN_NAME}:172.20.5.10"

  activitypods-frontend:
    image: activitypods/frontend
    depends_on:
      - activitypods-backend
    restart: always
    expose:
      - '5000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN_NAME}`)'
      - 'traefik.http.routers.frontend.entrypoints=websecure'
      - 'traefik.http.routers.frontend.tls.certresolver=myresolver'
    environment:
      REACT_APP_CONFIG_URL: 'https://${BACKEND_DOMAIN_NAME}/.well-known/config.js'

  wtmp-backend:
    image: activitypods/dev-welcometomyplace-backend
    depends_on:
      - fuseki
      - redis
    volumes:
      - ./data/wtmp/logs:/app/backend/logs
      - ./data/wtmp/jwt:/app/backend/jwt
    expose:
      - '3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.wtmp-backend.rule=(Host(`${WTMP_DOMAIN_NAME}`) && (PathPrefix(`/api`) || PathPrefix(`/.well-known`)))'
      - 'traefik.http.routers.wtmp-backend.entrypoints=websecure'
      - 'traefik.http.routers.wtmp-backend.tls.certresolver=myresolver'
    env_file:
      - .env.wtmp-backend
    # Redirect backend-to-backend calls to Traefik container
    extra_hosts:
      - "${BACKEND_DOMAIN_NAME}:172.20.5.10"
      - "${WTMP_DOMAIN_NAME}:172.20.5.10"

  wtmp-frontend:
    image: activitypods/dev-welcometomyplace-frontend
    depends_on:
      - wtmp-backend
    restart: always
    expose:
      - '4000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.wtmp-frontend.rule=Host(`${WTMP_DOMAIN_NAME}`)'
      - 'traefik.http.routers.wtmp-frontend.entrypoints=websecure'
      - 'traefik.http.routers.wtmp-frontend.tls.certresolver=myresolver'

  mutualaid-backend:
    image: activitypods/dev-mutualaid-backend
    depends_on:
      - fuseki
      - redis
    volumes:
      - ./data/mutualaid/logs:/app/backend/logs
      - ./data/mutualaid/jwt:/app/backend/jwt
    expose:
      - '3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mutualaid-backend.rule=(Host(`${MUTUALAID_DOMAIN_NAME}`) && (PathPrefix(`/api`) || PathPrefix(`/.well-known`)))'
      - 'traefik.http.routers.mutualaid-backend.entrypoints=websecure'
      - 'traefik.http.routers.mutualaid-backend.tls.certresolver=myresolver'
    env_file:
      - .env.mutualaid-backend
    # Redirect backend-to-backend calls to Traefik container
    extra_hosts:
      - "${BACKEND_DOMAIN_NAME}:172.20.5.10"
      - "${MUTUALAID_DOMAIN_NAME}:172.20.5.10"

  mutualaid-frontend:
    image: activitypods/dev-mutualaid-frontend
    depends_on:
      - mutualaid-backend
    restart: always
    expose:
      - '4000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mutualaid-frontend.rule=Host(`${MUTUALAID_DOMAIN_NAME}`)'
      - 'traefik.http.routers.mutualaid-frontend.entrypoints=websecure'
      - 'traefik.http.routers.mutualaid-frontend.tls.certresolver=myresolver'

  mastopod-backend:
    image: activitypods/dev-mastopod-backend
    depends_on:
      - fuseki
      - redis
    volumes:
      - ./data/mastopod/logs:/app/backend/logs
      - ./data/mastopod/jwt:/app/backend/jwt
    expose:
      - '3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mastopod-backend.rule=(Host(`${MASTOPOD_DOMAIN_NAME}`) && (PathPrefix(`/api`) || PathPrefix(`/.well-known`)))'
      - 'traefik.http.routers.mastopod-backend.entrypoints=websecure'
      - 'traefik.http.routers.mastopod-backend.tls.certresolver=myresolver'
    env_file:
      - .env.mastopod-backend
    # Redirect backend-to-backend calls to Traefik container
    extra_hosts:
      - "${BACKEND_DOMAIN_NAME}:172.20.5.10"
      - "${MASTOPOD_DOMAIN_NAME}:172.20.5.10"

  mastopod-frontend:
    image: activitypods/dev-mastopod-frontend
    depends_on:
      - mastopod-backend
    restart: always
    expose:
      - '4000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mastopod-frontend.rule=Host(`${MASTOPOD_DOMAIN_NAME}`)'
      - 'traefik.http.routers.mastopod-frontend.entrypoints=websecure'
      - 'traefik.http.routers.mastopod-frontend.tls.certresolver=myresolver'

  redis:
    image: redis
    expose:
      - '6379'
    volumes:
      - ./data/redis:/data:z
    command: [ 'redis-server', '--appendonly', 'yes' ]
    networks:
      default:
        ipv4_address: 172.20.5.11 # Fix Redis IP to make it easier to find it with a GUI

  arena:
    image: activitypods/arena
    restart: always
    volumes:
      - ./arena.json:/opt/arena/src/server/config/index.json
    depends_on:
      - redis
    ports:
      - '4567:4567'
    expose:
      - '4567'
    environment:
      REDIS_HOST: 'redis'

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.5.0/24
          gateway: 172.20.5.254
